name: "Solidity LSP Benchmark"
description: "Benchmark Solidity LSP servers using solidity-lsp-bench"

inputs:
  config:
    description: "Path to benchmark YAML config"
    required: false
    default: "benchmark.yaml"
  version:
    description: "Version of solidity-lsp-bench to use (e.g. v0.1.0, latest)"
    required: false
    default: "latest"
  servers:
    description: "Comma-separated list of servers to run (filters config). Empty = all."
    required: false
    default: ""

outputs:
  json:
    description: "Path to the benchmark JSON results file"
    value: ${{ steps.bench.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Determine platform
      id: platform
      shell: bash
      run: |
        case "$(uname -s)-$(uname -m)" in
          Linux-x86_64)  echo "target=x86_64-unknown-linux-gnu" >> "$GITHUB_OUTPUT" ;;
          Darwin-arm64)  echo "target=aarch64-apple-darwin" >> "$GITHUB_OUTPUT" ;;
          Darwin-x86_64) echo "target=x86_64-apple-darwin" >> "$GITHUB_OUTPUT" ;;
          *) echo "::error::Unsupported platform: $(uname -s)-$(uname -m)"; exit 1 ;;
        esac

    - name: Download solidity-lsp-bench
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        TARGET="${{ steps.platform.outputs.target }}"
        if [ "$VERSION" = "latest" ]; then
          gh release download --repo mmsaki/solidity-lsp-benchmarks -p "solidity-lsp-bench-*-${TARGET}.tar.gz" -D /tmp/bench-download
        else
          gh release download "$VERSION" --repo mmsaki/solidity-lsp-benchmarks -p "solidity-lsp-bench-*-${TARGET}.tar.gz" -D /tmp/bench-download
        fi
        tar xzf /tmp/bench-download/*.tar.gz -C /tmp/bench-download
        BENCH_DIR=$(find /tmp/bench-download -type d -name "solidity-lsp-bench-*" | head -1)
        echo "${BENCH_DIR}" >> "$GITHUB_PATH"

    - name: Run benchmarks
      id: bench
      shell: bash
      run: |
        SERVER_FLAGS=""
        if [ -n "${{ inputs.servers }}" ]; then
          IFS=',' read -ra SERVERS <<< "${{ inputs.servers }}"
          for s in "${SERVERS[@]}"; do
            SERVER_FLAGS="$SERVER_FLAGS -s $(echo $s | xargs)"
          done
        fi
        bench -c "${{ inputs.config }}" $SERVER_FLAGS 2>&1 | tee /tmp/bench-output.log
        # Extract the JSON path from bench output (line with "->")
        JSON_PATH=$(grep -oP '(?<=-> ).*\.json' /tmp/bench-output.log | tail -1)
        echo "json=${JSON_PATH}" >> "$GITHUB_OUTPUT"
